# utils/settings.py
# Constants for the game
SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
FPS = 60

# Player Settings 
PLAYER_HEALTH = 3
PLAYER_SPEED = 10
PLAYER_BULLET_SPEED = 1
PLAYER_SHOOTING_COOLDOWN = 0.001
PLAYER_SPECIAL_ATTACK = 10

# Asteroid Settings
ASTEROID_SPEED = 2
ASTEROID_HEALTH = 1
ASTEROID_FREQUENCY = 1
MAX_ASTEROIDS= 15
ASTEROID_COUNT= 0

# Helper Settings
HELPER_ITEM_CHANCE = 0.005
HELPER_ITEM_AMOUNT = 1
HELPER_SHIP_SPACING = 50
HELPER_HEALTH = 1
HELPER_SPEED = 5
HELPER_BULLET_SPEED = 2
HELPER_SHOOTING_COOLDOWN = 1 
HELPER_SHOOTING_RANGE = 100

# Health Item Settings
HEALTH_PACK_CHANCE = 0.001
HEALTH_PACK_AMOUNT = 1

# Colors
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
BACKGROUND_IMAGE_PATH='assets/images/background.png'
